// Automatically generated by https://codewitch-honey-crisis.github.io/gfx_web/icon-pack
// #define ICONS_IMPLEMENTATION in exactly one
// translation unit (.cpp file) before including this header

// USAGE:
#if 0
#define ICONS_IMPLEMENTATION
#include "icons.hpp"
#undef ICONS_IMPLEMENTATION
#endif
#ifndef ICONS_HPP
#define ICONS_HPP
#include <stdint.h>
#include <stddef.h>
#include "gfx_core.hpp"
#include "gfx_positioning.hpp"

constexpr static const uint16_t icons_height = 32;

/// @brief "Music" dimensions
constexpr static const gfx::sizef icons_music_dimensions(512,512);
/// @brief "Music" scaled dimensions
constexpr static const gfx::size16 icons_music_scaled_dimensions(32,32);
/// @brief "Music" target scale
constexpr static const float icons_music_scale = 0.0625;
/// @brief "Music" - a SVG vector icon
extern gfx::const_buffer_stream icons_music;
/// @brief "Lightbulb" dimensions
constexpr static const gfx::sizef icons_lightbulb_dimensions(384,512);
/// @brief "Lightbulb" scaled dimensions
constexpr static const gfx::size16 icons_lightbulb_scaled_dimensions(24,32);
/// @brief "Lightbulb" target scale
constexpr static const float icons_lightbulb_scale = 0.0625;
/// @brief "Lightbulb" - a SVG vector icon
extern gfx::const_buffer_stream icons_lightbulb;
/// @brief "Image" dimensions
constexpr static const gfx::sizef icons_image_dimensions(512,512);
/// @brief "Image" scaled dimensions
constexpr static const gfx::size16 icons_image_scaled_dimensions(32,32);
/// @brief "Image" target scale
constexpr static const float icons_image_scale = 0.0625;
/// @brief "Image" - a SVG vector icon
extern gfx::const_buffer_stream icons_image;
/// @brief "Circle Arrow Left" dimensions
constexpr static const gfx::sizef icons_circle_arrow_left_dimensions(512,512);
/// @brief "Circle Arrow Left" scaled dimensions
constexpr static const gfx::size16 icons_circle_arrow_left_scaled_dimensions(32,32);
/// @brief "Circle Arrow Left" target scale
constexpr static const float icons_circle_arrow_left_scale = 0.0625;
/// @brief "Circle Arrow Left" - a SVG vector icon
extern gfx::const_buffer_stream icons_circle_arrow_left;
#endif // ICONS_HPP

#ifdef ICONS_IMPLEMENTATION
static const char* icons_music_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBo"
    "x=\"0 0 512 512\"><path d=\"M499.1 6.3c8.1 6 12.9 15.6 12.9 25.7l0 72 0 264c0 44.2-"
    "43 80-96 80s-96-35.8-96-80s43-80 96-80c11.2 0 22 1.6 32 4.6L448 147 192 223.8 19"
    "2 432c0 44.2-43 80-96 80s-96-35.8-96-80s43-80 96-80c11.2 0 22 1.6 32 4.6L128 200"
    "l0-72c0-14.1 9.3-26.6 22.8-30.7l320-96c9.7-2.9 20.2-1.1 28.3 5z\"/></svg>";
gfx::const_buffer_stream icons_music
    ((const uint8_t*)icons_music_data, 358);

static const char* icons_lightbulb_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" vi"
    "ewBox=\"0 0 384 512\"><path d=\"M272 384c9.6-31.9 29.5-59.1 49.2-86.2c0 0 0 0 0 0c5"
    ".2-7.1 10.4-14.2 15.4-21.4c19.8-28.5 31.4-63 31.4-100.3C368 78.8 289.2 0 192 0S1"
    "6 78.8 16 176c0 37.3 11.6 71.9 31.4 100.3c5 7.2 10.2 14.3 15.4 21.4c0 0 0 0 0 0c"
    "19.8 27.1 39.7 54.4 49.2 86.2l160 0zM192 512c44.2 0 80-35.8 80-80l0-16-160 0 0 1"
    "6c0 44.2 35.8 80 80 80zM112 176c0 8.8-7.2 16-16 16s-16-7.2-16-16c0-61.9 50.1-112"
    " 112-112c8.8 0 16 7.2 16 16s-7.2 16-16 16c-44.2 0-80 35.8-80 80z\"/></svg>";
gfx::const_buffer_stream icons_lightbulb
    ((const uint8_t*)icons_lightbulb_data, 515);

static const char* icons_image_data = "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBo"
    "x=\"0 0 512 512\"><path d=\"M448 80c8.8 0 16 7.2 16 16l0 319.8-5-6.5-136-176c-4.5-5"
    ".9-11.6-9.3-19-9.3s-14.4 3.4-19 9.3L202 340.7l-30.5-42.7C167 291.7 159.8 288 152"
    " 288s-15 3.7-19.5 10.1l-80 112L48 416.3l0-.3L48 96c0-8.8 7.2-16 16-16l384 0zM64 "
    "32C28.7 32 0 60.7 0 96L0 416c0 35.3 28.7 64 64 64l384 0c35.3 0 64-28.7 64-64l0-3"
    "20c0-35.3-28.7-64-64-64L64 32zm80 192a48 48 0 1 0 0-96 48 48 0 1 0 0 96z\"/></svg>";
gfx::const_buffer_stream icons_image
    ((const uint8_t*)icons_image_data, 447);

static const char* icons_circle_arrow_left_data = "<svg xmlns=\"http://www.w3.org/2000"
    "/svg\" viewBox=\"0 0 512 512\"><path d=\"M512 256A256 256 0 1 0 0 256a256 256 0 1 0 "
    "512 0zM215 127c9.4-9.4 24.6-9.4 33.9 0s9.4 24.6 0 33.9l-71 71L392 232c13.3 0 24 "
    "10.7 24 24s-10.7 24-24 24l-214.1 0 71 71c9.4 9.4 9.4 24.6 0 33.9s-24.6 9.4-33.9 "
    "0L103 273c-9.4-9.4-9.4-24.6 0-33.9L215 127z\"/></svg>";
gfx::const_buffer_stream icons_circle_arrow_left
    ((const uint8_t*)icons_circle_arrow_left_data, 326);
#endif // ICONS_IMPLEMENTATION
